version: '3.8'

services:

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - microservices-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: platert
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: stats_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U platert -d stats_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  # F1 Service Backend
  f1-backend:
    build:
      context: ./f1-service/backend
      dockerfile: Dockerfile
    container_name: f1-backend
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - kafka
    volumes:
      - ./f1-service/backend/api:/app/api
    networks:
      - microservices-network
    restart: unless-stopped

  # F1 Service Frontend
  f1-frontend:
    build:
      context: ./f1-service/frontend
      dockerfile: Dockerfile
    container_name: f1-frontend
    ports:
      - "3000:80"
    depends_on:
      - f1-backend
    networks:
      - microservices-network
    restart: unless-stopped

  # Stats Service Backend
  stats-backend:
    build:
      context: ./stats-service/backend
      dockerfile: Dockerfile
    container_name: stats-backend
    ports:
      - "8001:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DATABASE_URL=postgresql://platert:password1@postgres:5432/stats_db
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    volumes:
      - ./stats-service/backend/api:/app/api
    networks:
      - microservices-network
    restart: unless-stopped

  # # Stats Service Frontend
  # stats-frontend:
  #   build:
  #     context: ./stats-service/frontend
  #     dockerfile: Dockerfile
  #   container_name: stats-frontend
  #   ports:
  #     - "3001:80"
  #   depends_on:
  #     - stats-backend
  #   networks:
  #     - microservices-network
  #   restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data: